namespace HKX2E
{
    public enum AnimationType : int
    {
        HK_UNKNOWN_ANIMATION = 0,
        HK_INTERLEAVED_ANIMATION = 1,
        HK_DELTA_COMPRESSED_ANIMATION = 2,
        HK_WAVELET_COMPRESSED_ANIMATION = 3,
        HK_MIRRORED_ANIMATION = 4,
        HK_SPLINE_COMPRESSED_ANIMATION = 5,
        HK_QUANTIZED_COMPRESSED_ANIMATION = 6,
    }
}

