namespace HKX2E
{
    public enum AttachmentType : sbyte
    {
        ATTACHMENT_TYPE_KEYFRAME_RIGID_BODY = 0,
        ATTACHMENT_TYPE_BALL_SOCKET_CONSTRAINT = 1,
        ATTACHMENT_TYPE_RAGDOLL_CONSTRAINT = 2,
        ATTACHMENT_TYPE_SET_WORLD_FROM_MODEL = 3,
        ATTACHMENT_TYPE_NONE = 4,
    }
}

