//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pandora.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class GUISettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static GUISettings defaultInstance = ((GUISettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GUISettings())));
        
        public static GUISettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PatchBoxNameColumnWidth {
            get {
                return ((double)(this["PatchBoxNameColumnWidth"]));
            }
            set {
                this["PatchBoxNameColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PatchBoxAuthorColumnWidth {
            get {
                return ((double)(this["PatchBoxAuthorColumnWidth"]));
            }
            set {
                this["PatchBoxAuthorColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PatchBoxVersionColumnWidth {
            get {
                return ((double)(this["PatchBoxVersionColumnWidth"]));
            }
            set {
                this["PatchBoxVersionColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double WindowWidth {
            get {
                return ((double)(this["WindowWidth"]));
            }
            set {
                this["WindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double WindowHeight {
            get {
                return ((double)(this["WindowHeight"]));
            }
            set {
                this["WindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PatchBoxPriorityColumnWidth {
            get {
                return ((double)(this["PatchBoxPriorityColumnWidth"]));
            }
            set {
                this["PatchBoxPriorityColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PatchBoxCodeColumnWidth {
            get {
                return ((double)(this["PatchBoxCodeColumnWidth"]));
            }
            set {
                this["PatchBoxCodeColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PatchBoxNameColumnVisible {
            get {
                return ((bool)(this["PatchBoxNameColumnVisible"]));
            }
            set {
                this["PatchBoxNameColumnVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PatchBoxAuthorColumnVisible {
            get {
                return ((bool)(this["PatchBoxAuthorColumnVisible"]));
            }
            set {
                this["PatchBoxAuthorColumnVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PatchBoxVersionColumnVisible {
            get {
                return ((bool)(this["PatchBoxVersionColumnVisible"]));
            }
            set {
                this["PatchBoxVersionColumnVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PatchBoxPriorityColumnVisible {
            get {
                return ((bool)(this["PatchBoxPriorityColumnVisible"]));
            }
            set {
                this["PatchBoxPriorityColumnVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PatchBoxCodeColumnVisible {
            get {
                return ((bool)(this["PatchBoxCodeColumnVisible"]));
            }
            set {
                this["PatchBoxCodeColumnVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsCompactRowHeight {
            get {
                return ((bool)(this["IsCompactRowHeight"]));
            }
            set {
                this["IsCompactRowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AppTheme {
            get {
                return ((int)(this["AppTheme"]));
            }
            set {
                this["AppTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GridLinesVisibility {
            get {
                return ((int)(this["GridLinesVisibility"]));
            }
            set {
                this["GridLinesVisibility"] = value;
            }
        }
    }
}
