name: publish_windows_self_contained

on:
  workflow_run:
    workflows: [build_release]
    types:
      - completed


env:
  build-mode: Release # Release | Debug
  # Explicit cache location to cache only nuget dependencies for this project.
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ["8.0.x"]

    steps:
      # Ref: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net#building-and-testing-your-code
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          
      - name: Get Latest Tag
        id: latesttag
        uses: WyriHaximus/github-action-get-previous-tag@v1.4.0
        with:
          fallback: 0.0.0
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: .NET Cache
        # If there is a cache here, it is restored, otherwise it is cached at the end.
        uses: actions/cache@v4
        with:
          # - Specify the same as `NUGET_PACKAGES`
          path: |
            ${{ github.workspace }}/.nuget/packages
            ${{ github.workspace }}/Pandora Behaviour Engine/bin
            ${{ github.workspace }}/Pandora Behaviour Engine/obj
            ${{ github.workspace }}/Pandora API/HKX2-Enhanced-Library/HKX2/bin
            ${{ github.workspace }}/Pandora API/HKX2-Enhanced-Library/HKX2/obj
            ${{ github.workspace }}/XML.Cake.NET/XML Cake/bin
            ${{ github.workspace }}/XML.Cake.NET/XML Cake/obj
          key: nuget-${{ runner.os }}-${{ matrix.dotnet-version }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Build Win-x86
        run: dotnet publish "./Pandora+.sln" --configuration ${{ env.build-mode }} -r win-x86 --self-contained

      - name: Build Win-x64
        run: dotnet publish "./Pandora+.sln" --configuration ${{ env.build-mode }} -r win-x64 --self-contained

      - name: Build Win-Arm64
        run: dotnet publish "./Pandora+.sln" --configuration ${{ env.build-mode }} -r win-arm64 --self-contained
      
      - name: Upload Win-x86 Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pandora.Behaviour.Engine.Win-x86
          path: |
            ./Pandora Behaviour Engine/bin/${{ env.build-mode }}/net8.0/win-x86/publish
            
      - name: Upload Win-x64 Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pandora.Behaviour.Engine.Win-x64
          path: |
            ./Pandora Behaviour Engine/bin/${{ env.build-mode }}/net8.0/win-x64/publish    
            
      - name: Upload Win-Arm64 Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pandora.Behaviour.Engine.Win-Arm64
          path: |
            ./Pandora Behaviour Engine/bin/${{ env.build-mode }}/net8.0/win-arm64/publish           
            
      - name: Download Linux-x64
        uses: actions/download-artifact@v4
        with:
         name: Pandora.Behaviour.Engine.Win-x86
         path: ./Output.Win-x86
         merge-multiple: true

      - name: Download Linux-Arm
        uses: actions/download-artifact@v4
        with:
         name: Pandora.Behaviour.Engine.Win-x64
         path: ./Output.Win-x64
         merge-multiple: true

      - name: Download Linux-Arm64
        uses: actions/download-artifact@v4
        with:
         name: Pandora.Behaviour.Engine.Win-Arm64
         path: ./Output.Win-Arm64
         merge-multiple: true
         
      - name: Zip Artifacts For Deployment
        run: |
          Compress-Archive -Path ./Output.Win-x86/* -Destination "./Output.Win-x86/Pandora_Behaviour_Engine_${{ steps.latesttag.outputs.tag }}_win-x86_net.zip"
          Compress-Archive -Path ./Output.Win-x64/* -Destination "./Output.Win-x64/Pandora_Behaviour_Engine_${{ steps.latesttag.outputs.tag }}_win-x64_net.zip"
          Compress-Archive -Path ./Output.Win-Arm64/* -Destination "./Output.Win-Arm64/Pandora_Behaviour_Engine_${{ steps.latesttag.outputs.tag }}_win-arm64_net.zip"
         
      - name: Upload Release
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         gh release upload "${{ steps.latesttag.outputs.tag }}" "./Output.Win-x86/Pandora_Behaviour_Engine_${{ steps.latesttag.outputs.tag }}_win-x86_net.zip"
         gh release upload "${{ steps.latesttag.outputs.tag }}" "./Output.Win-x64/Pandora_Behaviour_Engine_${{ steps.latesttag.outputs.tag }}_win-x64_net.zip"
         gh release upload "${{ steps.latesttag.outputs.tag }}" "./Output.Win-Arm64/Pandora_Behaviour_Engine_${{ steps.latesttag.outputs.tag }}_win-arm64_net.zip"
